# Generated by Django 5.2.7 on 2025-11-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="downloads",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="notes",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.subject"
            ),
        ),
    ]
